#if UNITY_EDITOR
namespace LuaGame.Editor.Codegen
{
	using System;
	using System.Collections.Generic;
	using System.IO;
	using System.Text;
	using Unity.Entities;
	using UnityEditor;
	using UnityEngine;

	public static class LuaBridgeGenerator
	{
		[MenuItem("Tools/LuaGame/Generate Component Bridges")]
		public static void GenerateAll()
		{
			var manifests = FindAllManifests();
			if (manifests.Count == 0)
			{
				Debug.Log("[LuaBridgeGenerator] No LuaCodegenManifest assets found. Create one via Assets > Create > LuaGame > Codegen Manifest.");
				return;
			}

			var totalGenerated = 0;
			foreach (var manifest in manifests)
			{
				totalGenerated += GenerateFromManifest(manifest);
			}
			Debug.Log($"[LuaBridgeGenerator] Generated {totalGenerated} bridge files.");
			AssetDatabase.Refresh();
		}

		static List<LuaCodegenManifest> FindAllManifests()
		{
			var results = new List<LuaCodegenManifest>();
			var guids = AssetDatabase.FindAssets("t:LuaCodegenManifest");
			foreach (var guid in guids)
			{
				var path = AssetDatabase.GUIDToAssetPath(guid);
				var manifest = AssetDatabase.LoadAssetAtPath<LuaCodegenManifest>(path);
				if (manifest != null)
					results.Add(manifest);
			}
			return results;
		}

		static int GenerateFromManifest(LuaCodegenManifest manifest)
		{
			var outputDir = manifest.outputDirectory;
			if (string.IsNullOrEmpty(outputDir))
			{
				var manifestPath = AssetDatabase.GetAssetPath(manifest);
				outputDir = Path.GetDirectoryName(manifestPath);
			}

			if (!Directory.Exists(outputDir))
				Directory.CreateDirectory(outputDir);

			var count = 0;
			foreach (var entry in manifest.entries)
			{
				if (entry.componentType == null)
					continue;

				var type = entry.componentType;
				if (!typeof(IComponentData).IsAssignableFrom(type))
				{
					Debug.LogWarning($"[LuaBridgeGenerator] {type.FullName} does not implement IComponentData, skipping.");
					continue;
				}

				var luaName = entry.luaName;
				if (string.IsNullOrEmpty(luaName))
					luaName = LuaComponentDescriptor.ToSnakeCase(type.Name);

				var code = GenerateBridge(type, luaName, entry.readOnly);
				var fileName = $"Lua{type.Name}Bridge.g.cs";
				var filePath = Path.Combine(outputDir, fileName);
				File.WriteAllText(filePath, code);
				count++;
				Debug.Log($"[LuaBridgeGenerator] Generated {fileName}");
			}
			return count;
		}

		public static string GenerateBridge(Type componentType, string luaName, bool readOnly)
		{
			var fields = LuaComponentDescriptor.Describe(componentType, readOnly);
			var typeName = componentType.Name;
			var fullTypeName = componentType.FullName.Replace("+", ".");
			var className = $"Lua{typeName}Bridge";

			var sb = new StringBuilder();
			sb.AppendLine("// Auto-generated by LuaBridgeGenerator. Do not edit.");
			sb.AppendLine("namespace LuaECS.Generated");
			sb.AppendLine("{");
			sb.AppendLine("\tusing AOT;");
			sb.AppendLine("\tusing Core;");
			sb.AppendLine("\tusing LuaNET.LuaJIT;");
			sb.AppendLine("\tusing Unity.Burst;");
			sb.AppendLine("\tusing Unity.Entities;");
			sb.AppendLine("\tusing Unity.Mathematics;");
			sb.AppendLine();

			// RuntimeInitializeOnLoadMethod for auto-registration
			sb.AppendLine($"\tpublic static class {className}");
			sb.AppendLine("\t{");
			sb.AppendLine($"\t\tstruct LookupMarker_{typeName} {{ }}");
			sb.AppendLine();
			sb.AppendLine($"\t\tstatic readonly SharedStatic<ComponentLookup<{fullTypeName}>> s_lookup =");
			sb.AppendLine($"\t\t\tSharedStatic<ComponentLookup<{fullTypeName}>>.GetOrCreate<LookupMarker_{typeName}, ComponentLookup<{fullTypeName}>>();");
			sb.AppendLine();

			// Auto-register on domain reload
			sb.AppendLine("#if UNITY_EDITOR");
			sb.AppendLine("\t\t[UnityEditor.InitializeOnLoadMethod]");
			sb.AppendLine("#endif");
			sb.AppendLine("\t\t[UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.SubsystemRegistration)]");
			sb.AppendLine($"\t\tstatic void AutoRegister()");
			sb.AppendLine("\t\t{");
			sb.AppendLine($"\t\t\tLuaComponentRegistry.RegisterBridge(");
			sb.AppendLine($"\t\t\t\t\"{luaName}\",");
			sb.AppendLine($"\t\t\t\tComponentType.ReadWrite<{fullTypeName}>(),");
			sb.AppendLine($"\t\t\t\tRegister,");
			sb.AppendLine($"\t\t\t\tUpdateLookup");
			sb.AppendLine("\t\t\t);");
			sb.AppendLine("\t\t}");
			sb.AppendLine();

			// Register function
			sb.AppendLine("\t\tpublic static void Register(lua_State l)");
			sb.AppendLine("\t\t{");
			sb.AppendLine("\t\t\tLua.lua_newtable(l);");
			foreach (var field in fields)
			{
				sb.AppendLine($"\t\t\tLua.lua_pushcfunction(l, Get_{field.fieldName});");
				sb.AppendLine($"\t\t\tLua.lua_setfield(l, -2, \"get_{field.luaName}\");");
				if (!field.isReadOnly)
				{
					sb.AppendLine($"\t\t\tLua.lua_pushcfunction(l, Set_{field.fieldName});");
					sb.AppendLine($"\t\t\tLua.lua_setfield(l, -2, \"set_{field.luaName}\");");
				}
			}
			sb.AppendLine($"\t\t\tLua.lua_setglobal(l, \"{luaName}\");");
			sb.AppendLine("\t\t}");
			sb.AppendLine();

			// UpdateLookup
			sb.AppendLine("\t\tpublic static void UpdateLookup(ref SystemState state)");
			sb.AppendLine("\t\t{");
			sb.AppendLine($"\t\t\ts_lookup.Data = state.GetComponentLookup<{fullTypeName}>({(readOnly ? "true" : "false")});");
			sb.AppendLine("\t\t}");
			sb.AppendLine();

			// Helper methods for compound types
			var needsFloat2 = false;
			var needsFloat3 = false;
			var needsFloat4 = false;
			var needsQuat = false;
			foreach (var field in fields)
			{
				if (field.luaFieldType == LuaFieldType.Float2) needsFloat2 = true;
				if (field.luaFieldType == LuaFieldType.Float3) needsFloat3 = true;
				if (field.luaFieldType == LuaFieldType.Float4) needsFloat4 = true;
				if (field.luaFieldType == LuaFieldType.Quaternion) needsQuat = true;
			}

			if (needsFloat2)
			{
				sb.AppendLine("\t\tstatic void PushFloat2(lua_State l, float2 v)");
				sb.AppendLine("\t\t{");
				sb.AppendLine("\t\t\tLua.lua_newtable(l);");
				sb.AppendLine("\t\t\tLua.lua_pushnumber(l, v.x); Lua.lua_setfield(l, -2, \"x\");");
				sb.AppendLine("\t\t\tLua.lua_pushnumber(l, v.y); Lua.lua_setfield(l, -2, \"y\");");
				sb.AppendLine("\t\t}");
				sb.AppendLine();
				sb.AppendLine("\t\tstatic float2 ReadFloat2(lua_State l, int idx)");
				sb.AppendLine("\t\t{");
				sb.AppendLine("\t\t\tvar r = float2.zero;");
				sb.AppendLine("\t\t\tif (idx < 0) idx = Lua.lua_gettop(l) + idx + 1;");
				sb.AppendLine("\t\t\tLua.lua_getfield(l, idx, \"x\"); if (Lua.lua_isnumber(l, -1) != 0) r.x = (float)Lua.lua_tonumber(l, -1); Lua.lua_pop(l, 1);");
				sb.AppendLine("\t\t\tLua.lua_getfield(l, idx, \"y\"); if (Lua.lua_isnumber(l, -1) != 0) r.y = (float)Lua.lua_tonumber(l, -1); Lua.lua_pop(l, 1);");
				sb.AppendLine("\t\t\treturn r;");
				sb.AppendLine("\t\t}");
				sb.AppendLine();
			}

			if (needsFloat3)
			{
				sb.AppendLine("\t\tstatic void PushFloat3(lua_State l, float3 v)");
				sb.AppendLine("\t\t{");
				sb.AppendLine("\t\t\tLua.lua_newtable(l);");
				sb.AppendLine("\t\t\tLua.lua_pushnumber(l, v.x); Lua.lua_setfield(l, -2, \"x\");");
				sb.AppendLine("\t\t\tLua.lua_pushnumber(l, v.y); Lua.lua_setfield(l, -2, \"y\");");
				sb.AppendLine("\t\t\tLua.lua_pushnumber(l, v.z); Lua.lua_setfield(l, -2, \"z\");");
				sb.AppendLine("\t\t}");
				sb.AppendLine();
				sb.AppendLine("\t\tstatic float3 ReadFloat3(lua_State l, int idx)");
				sb.AppendLine("\t\t{");
				sb.AppendLine("\t\t\tvar r = float3.zero;");
				sb.AppendLine("\t\t\tif (idx < 0) idx = Lua.lua_gettop(l) + idx + 1;");
				sb.AppendLine("\t\t\tLua.lua_getfield(l, idx, \"x\"); if (Lua.lua_isnumber(l, -1) != 0) r.x = (float)Lua.lua_tonumber(l, -1); Lua.lua_pop(l, 1);");
				sb.AppendLine("\t\t\tLua.lua_getfield(l, idx, \"y\"); if (Lua.lua_isnumber(l, -1) != 0) r.y = (float)Lua.lua_tonumber(l, -1); Lua.lua_pop(l, 1);");
				sb.AppendLine("\t\t\tLua.lua_getfield(l, idx, \"z\"); if (Lua.lua_isnumber(l, -1) != 0) r.z = (float)Lua.lua_tonumber(l, -1); Lua.lua_pop(l, 1);");
				sb.AppendLine("\t\t\treturn r;");
				sb.AppendLine("\t\t}");
				sb.AppendLine();
			}

			if (needsFloat4)
			{
				sb.AppendLine("\t\tstatic void PushFloat4(lua_State l, float4 v)");
				sb.AppendLine("\t\t{");
				sb.AppendLine("\t\t\tLua.lua_newtable(l);");
				sb.AppendLine("\t\t\tLua.lua_pushnumber(l, v.x); Lua.lua_setfield(l, -2, \"x\");");
				sb.AppendLine("\t\t\tLua.lua_pushnumber(l, v.y); Lua.lua_setfield(l, -2, \"y\");");
				sb.AppendLine("\t\t\tLua.lua_pushnumber(l, v.z); Lua.lua_setfield(l, -2, \"z\");");
				sb.AppendLine("\t\t\tLua.lua_pushnumber(l, v.w); Lua.lua_setfield(l, -2, \"w\");");
				sb.AppendLine("\t\t}");
				sb.AppendLine();
				sb.AppendLine("\t\tstatic float4 ReadFloat4(lua_State l, int idx)");
				sb.AppendLine("\t\t{");
				sb.AppendLine("\t\t\tvar r = float4.zero;");
				sb.AppendLine("\t\t\tif (idx < 0) idx = Lua.lua_gettop(l) + idx + 1;");
				sb.AppendLine("\t\t\tLua.lua_getfield(l, idx, \"x\"); if (Lua.lua_isnumber(l, -1) != 0) r.x = (float)Lua.lua_tonumber(l, -1); Lua.lua_pop(l, 1);");
				sb.AppendLine("\t\t\tLua.lua_getfield(l, idx, \"y\"); if (Lua.lua_isnumber(l, -1) != 0) r.y = (float)Lua.lua_tonumber(l, -1); Lua.lua_pop(l, 1);");
				sb.AppendLine("\t\t\tLua.lua_getfield(l, idx, \"z\"); if (Lua.lua_isnumber(l, -1) != 0) r.z = (float)Lua.lua_tonumber(l, -1); Lua.lua_pop(l, 1);");
				sb.AppendLine("\t\t\tLua.lua_getfield(l, idx, \"w\"); if (Lua.lua_isnumber(l, -1) != 0) r.w = (float)Lua.lua_tonumber(l, -1); Lua.lua_pop(l, 1);");
				sb.AppendLine("\t\t\treturn r;");
				sb.AppendLine("\t\t}");
				sb.AppendLine();
			}

			if (needsQuat)
			{
				sb.AppendLine("\t\tstatic void PushQuaternion(lua_State l, quaternion q)");
				sb.AppendLine("\t\t{");
				sb.AppendLine("\t\t\tLua.lua_newtable(l);");
				sb.AppendLine("\t\t\tLua.lua_pushnumber(l, q.value.x); Lua.lua_setfield(l, -2, \"x\");");
				sb.AppendLine("\t\t\tLua.lua_pushnumber(l, q.value.y); Lua.lua_setfield(l, -2, \"y\");");
				sb.AppendLine("\t\t\tLua.lua_pushnumber(l, q.value.z); Lua.lua_setfield(l, -2, \"z\");");
				sb.AppendLine("\t\t\tLua.lua_pushnumber(l, q.value.w); Lua.lua_setfield(l, -2, \"w\");");
				sb.AppendLine("\t\t}");
				sb.AppendLine();
				sb.AppendLine("\t\tstatic quaternion ReadQuaternion(lua_State l, int idx)");
				sb.AppendLine("\t\t{");
				sb.AppendLine("\t\t\tvar r = quaternion.identity;");
				sb.AppendLine("\t\t\tif (idx < 0) idx = Lua.lua_gettop(l) + idx + 1;");
				sb.AppendLine("\t\t\tLua.lua_getfield(l, idx, \"x\"); if (Lua.lua_isnumber(l, -1) != 0) r.value.x = (float)Lua.lua_tonumber(l, -1); Lua.lua_pop(l, 1);");
				sb.AppendLine("\t\t\tLua.lua_getfield(l, idx, \"y\"); if (Lua.lua_isnumber(l, -1) != 0) r.value.y = (float)Lua.lua_tonumber(l, -1); Lua.lua_pop(l, 1);");
				sb.AppendLine("\t\t\tLua.lua_getfield(l, idx, \"z\"); if (Lua.lua_isnumber(l, -1) != 0) r.value.z = (float)Lua.lua_tonumber(l, -1); Lua.lua_pop(l, 1);");
				sb.AppendLine("\t\t\tLua.lua_getfield(l, idx, \"w\"); if (Lua.lua_isnumber(l, -1) != 0) r.value.w = (float)Lua.lua_tonumber(l, -1); Lua.lua_pop(l, 1);");
				sb.AppendLine("\t\t\treturn r;");
				sb.AppendLine("\t\t}");
				sb.AppendLine();
			}

			// Generate getter/setter for each field
			foreach (var field in fields)
			{
				GenerateGetter(sb, field, fullTypeName);
				if (!field.isReadOnly)
					GenerateSetter(sb, field, fullTypeName);
			}

			sb.AppendLine("\t}");
			sb.AppendLine("}");

			return sb.ToString();
		}

		static void GenerateGetter(StringBuilder sb, LuaFieldDescriptor field, string fullTypeName)
		{
			sb.AppendLine($"\t\t[MonoPInvokeCallback(typeof(Lua.lua_CFunction))]");
			sb.AppendLine($"\t\tstatic int Get_{field.fieldName}(lua_State l)");
			sb.AppendLine("\t\t{");
			sb.AppendLine("\t\t\tvar entityId = (int)Lua.lua_tointeger(l, 1);");
			sb.AppendLine("\t\t\tvar entity = LuaECSBridge.GetEntityFromIdBurst(entityId);");
			sb.AppendLine("\t\t\tif (entity == Entity.Null || !s_lookup.Data.HasComponent(entity))");
			sb.AppendLine("\t\t\t{");
			sb.AppendLine("\t\t\t\tLua.lua_pushnil(l);");
			sb.AppendLine("\t\t\t\treturn 1;");
			sb.AppendLine("\t\t\t}");
			sb.AppendLine($"\t\t\tvar comp = s_lookup.Data[entity];");
			sb.AppendLine($"\t\t\t{LuaComponentDescriptor.GetPushCode(field.luaFieldType, $"comp.{field.fieldName}")}");
			sb.AppendLine("\t\t\treturn 1;");
			sb.AppendLine("\t\t}");
			sb.AppendLine();
		}

		static void GenerateSetter(StringBuilder sb, LuaFieldDescriptor field, string fullTypeName)
		{
			sb.AppendLine($"\t\t[MonoPInvokeCallback(typeof(Lua.lua_CFunction))]");
			sb.AppendLine($"\t\tstatic int Set_{field.fieldName}(lua_State l)");
			sb.AppendLine("\t\t{");
			sb.AppendLine("\t\t\tvar entityId = (int)Lua.lua_tointeger(l, 1);");
			sb.AppendLine("\t\t\tvar entity = LuaECSBridge.GetEntityFromIdBurst(entityId);");
			sb.AppendLine("\t\t\tif (entity == Entity.Null || !s_lookup.Data.HasComponent(entity))");
			sb.AppendLine("\t\t\t\treturn 0;");
			sb.AppendLine($"\t\t\tvar comp = s_lookup.Data[entity];");
			sb.AppendLine($"\t\t\tcomp.{field.fieldName} = {LuaComponentDescriptor.GetReadCode(field.luaFieldType, 2)};");
			sb.AppendLine($"\t\t\ts_lookup.Data[entity] = comp;");
			sb.AppendLine("\t\t\treturn 0;");
			sb.AppendLine("\t\t}");
			sb.AppendLine();
		}
	}
}
#endif
